### ISSUE TITLE
element-ui 表单校验 validate 会报错

### ISSUE THREAD

**Issue by qwfy5287** [dravenww/esbuild-plugin-vite-element-ui#1]
this.$refs.loginForm.validate((valid) => {

})

## 示例 点击登录触发表单验证会报错
https://github.com/qwfy5287/vue-admin-template-vite

## 错误信息
```
TypeError: external_async_validator_default.a is not a constructor
    at VueComponent.validate2
```

**Comment by dravenww** [comment]
这个，我也遇到了，正在尝试解决。

**Comment by dravenww** [comment]
把element-ui修改了一版esm版本的，可以尝试下，element-ui-es

**Comment by warwr1ck** [comment]
> 把element-ui修改了一版esm版本的，可以尝试下，element-ui-es

用element-ui-es替换element-ui之后，似乎又出现了以下问题
![image](https://user-images.githubusercontent.com/14226761/120128593-fc0fb180-c1f4-11eb-82dc-5d5918e661c4.png)

**Comment by qwfy5287** [comment]
> 这个，我也遇到了，正在尝试解决。

其他插件也会有问题，不知是 vite，还是esbuild，更新的问题，还是得从根源上解决。

目前我把项目锁定在 vite v2.2.4 可以运行。

**Comment by dravenww** [comment]
不是vite的问题，是esbuild的问题，使用element-ui-es搭配插件esbuild-plugin-vite-element-ui，可以成功

**Comment by qwfy5287** [comment]
@dravenww 
新版的vite解决问题了

fix: 升级到 vite v2.3.7, esbuild v0.12.7 for esm compatibility; 去掉 esbuild-plugin-vite-element-ui

示例
https://github.com/qwfy5287/vue-admin-template-vite
