### ISSUE TITLE
clone了下代码，$isServer还是报错

### ISSUE THREAD

**Issue by adi0754** [dravenww/esbuild-plugin-vite-element-ui#2]
```dom.js:19 Uncaught TypeError: Cannot read property '$isServer' of undefined```
哭了

**Comment by dravenww** [comment]
参见demo：https://github.com/tnfe/vite-vue2-pro，亲测可用

**Comment by OneSeven** [comment]
> 参见demo：[https://github.com/tnfe/vite-vue2-pro，亲测可用](https://github.com/tnfe/vite-vue2-pro%EF%BC%8C%E4%BA%B2%E6%B5%8B%E5%8F%AF%E7%94%A8)

兄弟，dev模型下，确实不能用，看能不能修复一下，另外你的element-ui-es项目，咋也有这个问题呢

**Comment by dravenww** [comment]
那是esbuild的问题，没办法啊。

**Comment by adi0754** [comment]
升级vite@2.3.7&&esbuild@0.12.7即可
[flx commit ](https://github.com/qwfy5287/vue-admin-template-vite/commit/dc550a168412f1737c67d8dec5fb3d4009259c32)
